#!/usr/bin/env python3
"""
Script to extract title data from input Excel files and customize output documents.
This script reads the Title sheet from Excel files and uses that data to customize
documents generated by the BillGenerator system.
"""

import pandas as pd
import os
import json
from pathlib import Path

def extract_title_data_from_excel(file_path):
    """
    Extract title data from an Excel file's Title sheet.
    
    Args:
        file_path (str): Path to the Excel file
        
    Returns:
        dict: Dictionary containing title data
    """
    try:
        # Read the Title sheet
        title_df = pd.read_excel(file_path, 'Title', header=None)
        
        # Process the title data
        title_data = {}
        for index, row in title_df.iterrows():
            if len(row) >= 2:
                key = str(row[0]).strip() if pd.notna(row[0]) else None
                value = row[1] if pd.notna(row[1]) else None
                
                if key and key != 'nan':
                    # Clean up the key name
                    clean_key = key.replace('*', '').replace(':', '').strip()
                    title_data[clean_key] = value
        
        return title_data
    except Exception as e:
        print(f"Error reading title data from {file_path}: {e}")
        return {}

def save_title_data_as_json(title_data, output_path):
    """
    Save title data to a JSON file.
    
    Args:
        title_data (dict): Title data dictionary
        output_path (str): Path to save the JSON file
    """
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(title_data, f, indent=2, default=str)
        print(f"Title data saved to: {output_path}")
    except Exception as e:
        print(f"Error saving title data to JSON: {e}")

def update_config_with_title_data(title_data, config_path='config/title_config.json'):
    """
    Update the title configuration file with data from the Excel file.
    
    Args:
        title_data (dict): Title data from Excel file
        config_path (str): Path to the title configuration file
    """
    try:
        # Load existing config if it exists
        if os.path.exists(config_path):
            with open(config_path, 'r', encoding='utf-8') as f:
                config = json.load(f)
        else:
            # Create default config structure
            config = {
                "title_data": {},
                "image_settings": {
                    "font_size": 40,
                    "text_positions": {
                        "project_name": [50, 50],
                        "contract_no": [50, 120],
                        "work_order_no": [50, 190]
                    },
                    "text_color": [255, 255, 255],
                    "shadow_color": [0, 0, 0],
                    "shadow_offset": [2, 2]
                }
            }
        
        # Map Excel title data to config fields
        mapping = {
            'Name of Work': 'Project Name',
            'Reference to work order or Agreement': 'Work Order No',
            'Agreement No': 'Contract No',
            'WORK ORDER AMOUNT RS': 'Work Order Amount',
            'TENDER PREMIUM %': 'Tender Premium %'
        }
        
        # Update title data in config
        for excel_key, config_key in mapping.items():
            if excel_key in title_data:
                config['title_data'][config_key] = title_data[excel_key]
        
        # Save updated config
        with open(config_path, 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=2, default=str)
        
        print(f"Title configuration updated: {config_path}")
        return config
    except Exception as e:
        print(f"Error updating title configuration: {e}")
        return None

def process_input_files(input_folder='TEST_INPUT_FILES'):
    """
    Process all Excel files in the input folder and extract title data.
    
    Args:
        input_folder (str): Path to the input folder containing Excel files
    """
    input_path = Path(input_folder)
    
    if not input_path.exists():
        print(f"Input folder not found: {input_folder}")
        return
    
    # Process each Excel file
    for file_path in input_path.glob('*.xlsx'):
        print(f"\nProcessing: {file_path.name}")
        
        # Extract title data
        title_data = extract_title_data_from_excel(file_path)
        
        if title_data:
            # Save raw title data as JSON
            output_file = f"OUTPUT_FILES/{file_path.stem}_title_data.json"
            os.makedirs(os.path.dirname(output_file), exist_ok=True)
            save_title_data_as_json(title_data, output_file)
            
            # Update title configuration
            update_config_with_title_data(title_data)
            
            # Print extracted data
            print("Extracted title data:")
            for key, value in title_data.items():
                print(f"  {key}: {value}")
        else:
            print("  No title data found")

def main():
    """Main function to process input files and extract title data."""
    print("Customizing title from input Excel files...")
    print("=" * 50)
    
    # Process input files
    process_input_files()
    
    print("\n" + "=" * 50)
    print("Title customization process completed!")

if __name__ == "__main__":
    main()