#!/usr/bin/env python3
"""
Batch Processing Test - Process all files in TEST_INPUT_FILES
Simulates batch processing mode functionality
"""
import sys
from pathlib import Path
import pandas as pd
from datetime import datetime
import zipfile
import io

# Add core to path
sys.path.insert(0, str(Path(__file__).parent))

def print_header(text):
    """Print formatted header"""
    print("\n" + "=" * 80)
    print(f"  {text}")
    print("=" * 80)

def print_section(text):
    """Print formatted section"""
    print(f"\n{'─' * 80}")
    print(f"  {text}")
    print(f"{'─' * 80}")

def process_batch(files, output_base_dir):
    """Process multiple files in batch"""
    from core.processors.excel_processor import ExcelProcessor
    from core.utils.output_manager import OutputManager
    from docx import Document
    
    results = []
    total_files = len(files)
    
    print_section(f"Processing {total_files} files in batch mode")
    
    for i, file_path in enumerate(files, 1):
        print(f"\n[{i}/{total_files}] Processing: {file_path.name}")
        
        result = {
            'file': file_path.name,
            'success': False,
            'html': False,
            'word': False,
            'pdf': False,
            'output_folder': None,
            'errors': []
        }
        
        try:
            # Initialize output manager
            output_mgr = OutputManager(source_filename=file_path.stem)
            output_folder = output_mgr.get_output_folder()
            result['output_folder'] = str(output_folder)
            
            # Read Excel file
            df = pd.read_excel(file_path, sheet_name=0)
            print(f"  ✅ Read: {len(df)} rows, {len(df.columns)} columns")
            
            # Extract bill info
            bill_info = {
                'bill_number': 'Unknown',
                'bill_type': 'Final' if 'Final' in file_path.name else 'Running'
            }
            
            # Try to find bill number
            for idx, row in df.iterrows():
                if 'Bill Number' in str(row.values):
                    try:
                        bill_info['bill_number'] = str(row.values[1]) if len(row.values) > 1 else 'N/A'
                    except:
                        pass
                    break
            
            # Generate HTML
            try:
                html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Bill - {bill_info['bill_number']}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        h1 {{ color: #2c3e50; }}
        .info {{ background: #ecf0f1; padding: 15px; border-radius: 5px; margin: 10px 0; }}
        table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
        th, td {{ border: 1px solid #bdc3c7; padding: 10px; text-align: left; }}
        th {{ background-color: #3498db; color: white; }}
        .footer {{ margin-top: 30px; padding: 15px; background: #ecf0f1; text-align: center; }}
    </style>
</head>
<body>
    <h1>📄 Bill Report - {bill_info['bill_number']}</h1>
    
    <div class="info">
        <p><strong>Bill Type:</strong> {bill_info['bill_type']}</p>
        <p><strong>Source File:</strong> {file_path.name}</p>
        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <p><strong>Total Rows:</strong> {len(df)}</p>
        <p><strong>Total Columns:</strong> {len(df.columns)}</p>
    </div>
    
    <h2>Data Summary</h2>
    <table>
        <tr>
            <th>Column</th>
            <th>Sample Data</th>
        </tr>
"""
                
                for col in df.columns[:5]:
                    sample = str(df[col].iloc[0]) if len(df) > 0 else 'N/A'
                    html_content += f"""
        <tr>
            <td>{col}</td>
            <td>{sample[:50]}...</td>
        </tr>
"""
                
                html_content += """
    </table>
    
    <div class="footer">
        <p>Generated by BillGenerator Unified - Batch Processing Mode</p>
        <p>PWD Udaipur | Initiative of Mrs. Premlata Jain, AAO</p>
    </div>
</body>
</html>
"""
                
                html_path = output_mgr.save_text_file(html_content, 'bill_report', '.html')
                result['html'] = True
                print(f"  ✅ HTML: {html_path.name}")
                
            except Exception as e:
                result['errors'].append(f"HTML: {str(e)}")
                print(f"  ⚠️  HTML failed: {str(e)[:50]}")
            
            # Generate Word document
            try:
                doc = Document()
                doc.add_heading(f'Bill Report - {bill_info["bill_number"]}', 0)
                
                doc.add_heading('Bill Information', level=1)
                doc.add_paragraph(f'Bill Type: {bill_info["bill_type"]}')
                doc.add_paragraph(f'Source File: {file_path.name}')
                doc.add_paragraph(f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
                
                doc.add_heading('Data Summary', level=1)
                doc.add_paragraph(f'Total Rows: {len(df)}')
                doc.add_paragraph(f'Total Columns: {len(df.columns)}')
                
                if len(df) > 0:
                    doc.add_heading('Sample Data', level=2)
                    table = doc.add_table(rows=min(6, len(df)+1), cols=min(3, len(df.columns)))
                    table.style = 'Light Grid Accent 1'
                    
                    for i, col in enumerate(df.columns[:3]):
                        table.rows[0].cells[i].text = str(col)
                    
                    for i in range(min(5, len(df))):
                        for j in range(min(3, len(df.columns))):
                            table.rows[i+1].cells[j].text = str(df.iloc[i, j])[:50]
                
                doc.add_page_break()
                doc.add_paragraph('Generated by BillGenerator Unified - Batch Processing Mode')
                doc.add_paragraph('PWD Udaipur | Initiative of Mrs. Premlata Jain, AAO')
                
                word_path = output_folder / 'bill_report.docx'
                doc.save(word_path)
                result['word'] = True
                print(f"  ✅ Word: {word_path.name}")
                
            except Exception as e:
                result['errors'].append(f"Word: {str(e)}")
                print(f"  ⚠️  Word failed: {str(e)[:50]}")
            
            # Try PDF (will fail on Windows)
            try:
                from weasyprint import HTML
                if result['html']:
                    pdf_path = output_folder / 'bill_report.pdf'
                    HTML(string=html_content).write_pdf(pdf_path)
                    result['pdf'] = True
                    print(f"  ✅ PDF: {pdf_path.name}")
            except Exception as e:
                print(f"  ⚠️  PDF skipped (expected on Windows)")
            
            result['success'] = result['html'] or result['word']
            
        except Exception as e:
            result['errors'].append(f"Processing: {str(e)}")
            print(f"  ❌ Error: {str(e)}")
        
        results.append(result)
    
    return results

def create_batch_zip(results, output_base_dir):
    """Create ZIP file with all outputs"""
    print_section("Creating Batch ZIP Archive")
    
    zip_buffer = io.BytesIO()
    files_added = 0
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        for result in results:
            if result['output_folder']:
                output_folder = Path(result['output_folder'])
                if output_folder.exists():
                    for file_path in output_folder.glob('*'):
                        if file_path.is_file():
                            arcname = f"{output_folder.name}/{file_path.name}"
                            zip_file.write(file_path, arcname)
                            files_added += 1
                            print(f"  ✅ Added: {arcname}")
    
    if files_added > 0:
        zip_filename = f"batch_output_{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip"
        zip_path = Path(output_base_dir) / zip_filename
        
        with open(zip_path, 'wb') as f:
            f.write(zip_buffer.getvalue())
        
        print(f"\n  📦 ZIP Created: {zip_path}")
        print(f"  📊 Files in ZIP: {files_added}")
        print(f"  💾 Size: {zip_path.stat().st_size / 1024:.1f} KB")
        
        return zip_path
    
    return None

def main():
    """Main batch processing test"""
    print_header("🚀 BATCH PROCESSING TEST - BILLGENERATOR UNIFIED")
    print(f"  Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"  Mode: Batch Processing")
    
    # Load configuration
    print_section("Loading Configuration")
    
    try:
        from core.config.config_loader import ConfigLoader
        config = ConfigLoader.load_from_file('config/v01.json')
        print(f"  ✅ Config: {config.app_name} v{config.version}")
        print(f"  ✅ Batch Processing: {'Enabled' if config.features.batch_processing else 'Disabled'}")
    except Exception as e:
        print(f"  ❌ Config error: {str(e)}")
        return False
    
    # Scan test files
    print_section("Scanning Test Files")
    
    test_input_dir = Path("TEST_INPUT_FILES")
    excel_files = sorted(test_input_dir.glob("*.xlsx"))
    
    if not excel_files:
        print(f"  ❌ No Excel files found")
        return False
    
    print(f"  ✅ Found {len(excel_files)} files:")
    for i, file in enumerate(excel_files, 1):
        size_kb = file.stat().st_size / 1024
        print(f"    {i}. {file.name:40s} ({size_kb:6.1f} KB)")
    
    # Process batch
    print_header("🔄 BATCH PROCESSING")
    
    output_base_dir = Path("OUTPUT")
    results = process_batch(excel_files, output_base_dir)
    
    # Create ZIP
    zip_path = create_batch_zip(results, output_base_dir)
    
    # Generate summary
    print_header("📊 BATCH PROCESSING SUMMARY")
    
    total = len(results)
    successful = sum(1 for r in results if r['success'])
    html_count = sum(1 for r in results if r['html'])
    word_count = sum(1 for r in results if r['word'])
    pdf_count = sum(1 for r in results if r['pdf'])
    
    print(f"\n  📁 Total Files: {total}")
    print(f"  ✅ Successful: {successful}/{total}")
    print(f"  🌐 HTML Generated: {html_count}/{total}")
    print(f"  📄 Word Generated: {word_count}/{total}")
    print(f"  📑 PDF Generated: {pdf_count}/{total}")
    
    success_rate = (successful / total * 100) if total > 0 else 0
    print(f"\n  📊 Success Rate: {success_rate:.0f}%")
    
    # Detailed results
    print_section("Detailed Results")
    
    print(f"\n  {'File':<40} {'HTML':>6} {'Word':>6} {'PDF':>6} {'Status':>10}")
    print(f"  {'-'*40} {'-'*6} {'-'*6} {'-'*6} {'-'*10}")
    
    for result in results:
        html_status = '✅' if result['html'] else '❌'
        word_status = '✅' if result['word'] else '❌'
        pdf_status = '✅' if result['pdf'] else '⚠️'
        overall = '✅ OK' if result['success'] else '❌ FAIL'
        
        print(f"  {result['file']:<40} {html_status:>6} {word_status:>6} {pdf_status:>6} {overall:>10}")
    
    # Output locations
    print_section("Output Locations")
    
    for result in results:
        if result['output_folder']:
            print(f"  📁 {result['output_folder']}")
    
    if zip_path:
        print(f"\n  📦 Batch ZIP: {zip_path}")
    
    # Final status
    print_header("✅ BATCH PROCESSING COMPLETED")
    
    if success_rate >= 90:
        print(f"\n  🎉 EXCELLENT! {success_rate:.0f}% success rate")
        print(f"  ✅ Batch processing working perfectly")
        print(f"  ✅ All outputs generated successfully")
    elif success_rate >= 70:
        print(f"\n  ✅ GOOD! {success_rate:.0f}% success rate")
        print(f"  ⚠️  Some files had issues")
        print(f"  💡 Review warnings above")
    else:
        print(f"\n  ⚠️  {success_rate:.0f}% success rate")
        print(f"  ❌ Multiple files failed")
        print(f"  💡 Check errors above")
    
    print_section("Next Steps")
    
    print(f"\n  1. 📂 Check output files:")
    print(f"     ls OUTPUT/*/")
    
    print(f"\n  2. 📦 Extract ZIP file:")
    if zip_path:
        print(f"     unzip {zip_path.name}")
    
    print(f"\n  3. 🌐 Test in Streamlit UI:")
    print(f"     Open http://localhost:8501")
    print(f"     Select 'Batch Processing' mode")
    print(f"     Upload multiple files")
    
    print(f"\n  4. 🚀 Deploy to production:")
    print(f"     git add .")
    print(f"     git commit -m 'Batch processing tested and working'")
    print(f"     git push")
    
    print("\n" + "=" * 80 + "\n")
    
    return success_rate >= 70

if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\n⚠️  Test interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Fatal error: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
